# Generated by Django 3.2.5 on 2021-07-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Monthly_rent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Make'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='Building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.building'),
        ),
    ]
