# Generated by Django 3.2.5 on 2021-07-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210716_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='Building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.building'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
