# Generated by Django 3.2.5 on 2021-07-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210716_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='Building',
        ),
    ]
