# Generated by Django 3.2.5 on 2021-07-16 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_tenant_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='Building',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='management.building'),
            preserve_default=False,
        ),
    ]
