# Generated by Django 3.2.5 on 2021-07-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_tenant_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='Building',
        ),
        migrations.AlterField(
            model_name='building',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
