# Generated by Django 3.2.5 on 2021-07-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210716_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='Number',
            field=models.IntegerField(max_length=100),
        ),
    ]
